### ISSUE TITLE
install testing version of redis

### ISSUE THREAD

**Issue by robomotic** [DavidWittman/ansible-redis#104]
Hello there,
this is wonderful but I have noticed if I put as version the testing one which is 3.2 that is not in the standard release url it will not fetch it, so this version will be fine:
http://download.redis.io/releases/redis-3.0.7.tar.gz
But if I type 3.2.0-rc3 which is in the archive the path will be:
https://github.com/antirez/redis/archive/3.2.0-rc3.tar.gz
Could you do a patch to allow also to fetch newer versions from the archive which is here?
Let me know!

**Comment by DavidWittman** [comment]
@robomotic Try overriding `redis_download_url` as well as `redis_version`.

``` yaml
- role: DavidWittman.redis
  redis_version: 3.20-rc3
  redis_download_url: https://github.com/antirez/redis/archive/3.2.0-rc3.tar.gz
```
