### ISSUE TITLE
unable to install redis sentinel on redis master and/or slave

### ISSUE THREAD

**Issue by sylvek** [DavidWittman/ansible-redis#110]
Hello,

I use a configuration like that.
```
[redis-master]
redis-1

[redis-slave]
redis-2
redis-3

[redis-sentinel]
redis-1 redis_sentinel=True
redis-2 redis_sentinel=True
redis-3 redis_sentinel=True
```
in this case, sentinel configuration override the master/slave configuration.
i need to play 2 times my ansible scripts (the second time i have to comment the redis-sentinel section) to have a correct setup.

**Comment by sylvek** [comment]
after reading sources, but it's possible to have both on the same host…
```
…
- include: server.yml
  when: not redis_sentinel
  tags:
    - config

- include: sentinel.yml
  when: redis_sentinel
  tags:
    - config
…
```

**Comment by DavidWittman** [comment]
@sylvek The idea here is that you can run this role twice if you wish to install Sentinel and Server on the same host. Here's a very basic example:

``` yaml
- hosts: all
  roles:
    - role: DavidWittman.redis
    - role: DavidWittman.redis
      redis_sentinel: true
```

This is how it has worked for a long time, and I don't see any compelling reason for changing it right now. If you have some particular issue with this method (other than it changes the way you're doing things now), let me know and I'll be happy to review. In the meantime, I'm going to close this issue for now.

**Comment by sylvek** [comment]
Thank you!

**Comment by mcheriyath** [comment]
@DavidWittman Can you please let me know how should I pass the tags while I run the playbook to achieve this?

Is it like the below?
ansible-playbook -i /etc/ansible/hosts redis.yml --tags download,install,config

**Comment by mcheriyath** [comment]
I have figured it out. 

First run should have all the tasks mentioned including the redis_sentinel_monitors[redis-sentinel] and then in the second run we need to comment out the redis-sentinal host part and re-run the same.

The playbook can be run without passing any tags.
ansible-playbook -i /etc/ansible/hosts redis.yml

@DavidWittman  Thanks for this Amazing ansible role!

**Comment by wesgarrison** [comment]
Here's the syntax I needed to get it working:

```yaml
- hosts: all
  roles:
    - role: DavidWittman.redis
      vars:
        redis_sentinel: false

    - role: DavidWittman.redis
      vars:
        redis_sentinel: true
```

This should also work, depending on your version of ansible.
```yaml
roles:
  - { role: DavidWittman.redis, vars: { redis_sentinel: "false" } }
  - { role: DavidWittman.redis, vars: { redis_sentinel: "true" } }
```
