### ISSUE TITLE
Question: can server and sentinel share the same node?

### ISSUE THREAD

**Issue by sberserker** [DavidWittman/ansible-redis#122]
Is it possible to install server and sentinel on the same node?
I know it is not ideal but can be useful for minimalistic 3 node setup.

**Comment by DavidWittman** [comment]
@sberserker Yes this is possible. You can just run this role twice against the server. Here's an example:

``` yaml
- hosts: foo.example.com
  roles:
    - role: DavidWittman.redis
    - role: DavidWittman.redis
      redis_sentinel: yes
```
