### ISSUE TITLE
Support run redis as root

### ISSUE THREAD

**Issue by fuku2014** [DavidWittman/ansible-redis#136]
I want to run redis as root.
```
redis_user: root
```
But task is Failed.
```
fatal: [myredis]: FAILED! => {"changed": false, "failed": true, "msg": "usermod: user root is currently used by process 1\n", "name": "root", "rc": 8}
```
How about fixing like this?

```
- name: add redis user
  user:
    name: "{{ redis_user }}"
    comment: "Redis"
    home: "{{ redis_install_dir }}"
    shell: /bin/false
    system: yes
  when: redis_user != "root"
```
