### ISSUE TITLE
dry run is not supported?

### ISSUE THREAD

**Issue by fuku2014** [DavidWittman/ansible-redis#148]
I want to run check mode, but this role is failure.

```yaml
---
- hosts: localhost
  remote_user: root
  roles:
    - DavidWittman.redis
  vars:
    redis_version: 2.8.17
  serial: 1
```

$ ansible-playbook  -i local -C site.yml

```
TASK [DavidWittman.redis : extract redis tarball] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Source '/usr/local/src/redis-2.8.17.tar.gz' does not exist"}

```
