### ISSUE TITLE
Recommended way to upgrade Redis?

### ISSUE THREAD

**Issue by thbar** [DavidWittman/ansible-redis#174]
If I started with say `redis_version: 3.2.6`, and want to upgrade later, are there specific things to take care about before installing the new version? (e.g. should I manually shutdown Redis)?

Thanks for any guidance you'll be able to provide, and for this nice role!

**Comment by mikegleasonjr** [comment]
friendly ping @DavidWittman

**Comment by thbar** [comment]
If anyone has feedback, I'm still interested!

**Comment by thbar** [comment]
I will need to address this in automated fashion in a few months. If someone has already done that & has a few guidelines (@DavidWittman maybe?), I'll use that as a starting point, and will contribute back a PR with some notes if you think it's worth sharing!

**Comment by jdivy** [comment]
For what it's worth, the only way I was able to get an upgrade working with as little friction as possible was to override/set the redis_install_dir variable to `/opt/redis_{{ redis_version }}`.  I've been testing it with a replica and so far so good, though my use case may be more flexible (e.g. not 100% uptime critical) than others.

**Comment by bew** [comment]
Agree with @jdivy, changing the `redis_install_dir` will correctly install the specified new version of redis.

What about the configuration? For example when you have a `redis-sentinel`, how to upgrade the redis version without overwriting its configuration?

I think we could use a `redis_dont_overwrite_configs` variable that would be checked before writing the `redis_PORT.conf` & `sentinel_PORT.conf` files. What do you think?

**Comment by thbar** [comment]
Thanks @jdivy & @bew ; I tested today, and if I just upgrade the version, the file under `/opt/redis/bin/redis-server` (which is referenced by `/etc/systemd/system/redis_6379.service`) still points to the old version. The role (1.2.6) will states that everything went fine, but actually the old version remains running.

Another caveat is that if you did not use that technique (e.g. attempted to upgrade without a dedicated folder), then use the technique, it won't work either (which I saw thanks to using a snapshot).

In all cases, thanks to both of you, because it looks like the upgrade went fine on a test machine.

It should probably be documented in a way or another!

**Comment by thbar** [comment]
Adding that actually, I also had to force a reload when moving from the "legacy" `/opt/redis` to `/opt/redis_5.0.5`, or the old version would keep running. In case it helps anyone, I use this custom task & variables:

Variables:

```yaml
remove_legacy_opt_redis: true
```

```yaml
- name: Remove legacy /opt/redis (replaced by version-specific one)
  file: path=/opt/redis state=absent
  when: remove_legacy_opt_redis
  # required otherwise the previous one will keep running
  notify: "restart redis {{ redis_port }}"
```

**Comment by thbar** [comment]
Closing for now - someone with the need will likely stumble upon this. A doc PR could be useful later though!

**Comment by thbar** [comment]
Upgrading from v6 to v7 at the moment, I found the following snippets useful if this helps someone:

```yml
- name: Evaluate running Redis version
  shell: redis-cli INFO | grep redis_version | cut -d':' -f2
  register: detected_running_redis_version
  changed_when: false

- name: Restart Redis if version has changed
  service: name={{ redis_service_name }} state=restarted
  when: detected_running_redis_version.stdout != redis_version
```
