### ISSUE TITLE
Installing sentinel wipes out old configuration

### ISSUE THREAD

**Issue by bsener** [DavidWittman/ansible-redis#184]
I want to setup a cluster using 3 nodes. 1 master and 2 slaves. Also, I want to install sentinel in all nodes. 
After installation Redis-Server setup is overriden. How can I achieve to install all nodes as sentinel without overriding server configuration?

Playbook

```
- name: configure the master redis server
  hosts: redis_master
  roles:
    - role: DavidWittman.redis
    - role: DavidWittman.redis
      redis_sentinel: yes

- name: configure redis slaves
  hosts: redis_slave
  vars:
    - redis_slaveof: 10.1.37.248 6379
  roles:
    - role: DavidWittman.redis
    - role: DavidWittman.redis
      redis_sentinel: yes

```

Inventory:

```
redis:
    children:
        redis_master:
            hosts:
                  10.1.37.248:
        redis_slave:
            hosts:
                10.1.37.249:
                10.1.37.250:
        redis_sentinel:
            hosts:
              10.1.37.248:
              10.1.37.249:
              10.1.37.250:
```

**Comment by roadrunner** [comment]
@bsener did you find any solution?
i ran into this weird problem as well.

**Comment by roadrunner** [comment]
applying same role with `redis_sentinel` variable seems working

```
---
- name: configure the master redis server
  hosts: master
  roles:
    - DavidWittman.redis
    - { role: DavidWittman.redis, redis_sentinel: true }

- name: configure redis slaves
  hosts: slave
  vars:
    - redis_slaveof: redis-master 6379
  roles:
    - DavidWittman.redis
    - { role: DavidWittman.redis, redis_sentinel: true }
```
