### ISSUE TITLE
Error: handler 'restart redis 6379' was not found

### ISSUE THREAD

**Issue by alibo** [DavidWittman/ansible-redis#193]
Unfortunately, I get this error with Ansible 2.6.2:

```bash
TASK [DavidWittman.redis : create redis config file] **************************************************************
ERROR! The requested handler 'restart redis 6379' was not found in either the main handlers list nor in the listening handlers list
```

Here is the playbook:

```yaml
---
- name: Configure Redis
  hosts: all
  remote_user: root
  vars:
    - redis_slaveof: 192.168.1.100 6379
    - redis_version: 4.0.10
    - redis_port: 6379
    - redis_maxclients: 10000
    - redis_tcp_backlog: 5000
    - redis_bind: 127.0.0.1
    - redis_save:
      - ""
  roles:
    - redis
```

It seems Ansible doesn't pass the variable `redis_port` to the handler, so it can't find the handler `restart redis 6379`:
https://github.com/DavidWittman/ansible-redis/blob/1.2.5/handlers/main.yml#L2

Is there any workaround for this issue?

**Comment by alibo** [comment]
It doesn't resolve the handler's name, but it works:

```bash
RUNNING HANDLER [DavidWittman.redis : restart redis {{ redis_port }}] *********************************************
changed: [node-1] => {"changed": true, "name": "redis_6379", "state": "started", "status": {"ActiveEnterTimestampMonotonic": "0", "ActiveExitTimestampMonotonic": "0" ...
```

However if I change the playbook from:

```yaml
- name: Configure a slave instance of Redis master
  hosts: all
  remote_user: root
  vars:
    - redis_slaveof: "{{ redis_cache_slave_of }}"
    - redis_version: "{{ redis_cache_version }}"
    - redis_port: 6379
  roles:
    - DavidWittman.redis
```

to:

```yaml
- name: Configure a slave instance of Redis master
  hosts: all
  remote_user: root
  vars:
    - redis_slaveof: "{{ redis_cache_slave_of }}"
    - redis_version: "{{ redis_cache_version }}"
    - redis_port: "{{ redis_cache_port }}"
  roles:
    - DavidWittman.redis


# group_vars/all
redis_cache_port: 6379

```

```bash
TASK [DavidWittman.redis : create pid directory if it does not exist] *********************************************
skipping: [node-1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [DavidWittman.redis : create redis config file] **************************************************************
ERROR! The requested handler 'restart redis 6379' was not found in either the main handlers list nor in the listening handlers list
```

It won't work anymore. It's completely weird :( 

I reopen the issue.
