### ISSUE TITLE
1.2.9 is not found in Ansible Galaxy

### ISSUE THREAD

**Issue by FuhuXia** [DavidWittman/ansible-redis#274]
Got following error when using `1.2.9`.
```
davidwittman.redis was NOT installed successfully: - the specified version (1.2.9) 
of davidwittman.redis was not found in the list of available versions
```

Looking at https://galaxy.ansible.com/DavidWittman/redis, the lastest is still `1.2.8`

**Comment by AidasK** [comment]
Is there any workaround while we are waiting for this to be released?

**Comment by AidasK** [comment]
Actually it's as easy as this:
```yml
- name: DavidWittman.redis
  version: 1.2.9
  src: https://github.com/DavidWittman/ansible-redis
```
