### ISSUE TITLE
install_from_source.yml missing from repo

### ISSUE THREAD

**Issue by Theoooooo** [DavidWittman/ansible-redis#283]
Hello

Since the version 1.2.10, a new task has been added inside the ansible repo to be able to install the role from source instead from repo, but the file is missing inside the repo :

```
- include: install_from_source.yml
  when: redis_install_from_source
  tags:
    - install
```

But the file is missing from the tasks directory :
![image](https://user-images.githubusercontent.com/33425208/205594412-c119c165-3329-44aa-89d1-0d316b7e2837.png)

Output from ansible :
![image](https://user-images.githubusercontent.com/33425208/205594783-2cc0b6da-f3dc-4059-9c88-65daef68a77d.png)

Is this is the normal behavior ?
