### ISSUE TITLE
README role name is incorrect?

### ISSUE THREAD

**Issue by kenperkins** [DavidWittman/ansible-redis#49]
From the README:
```
$ ansible-galaxy install DavidWittman.redis
```

```yaml
---
- hosts: redis01.example.com
  vars:
    - redis_bind: 127.0.0.1
  roles:
    - redis
```

When I run that:

```
/data/src/my-app [master]* $ ansible-playbook --i deployment/hosts.test deployment/setup.yml
ERROR: cannot find role in /data/src/my-app/deployment/roles/redis or /data/src/my-app/deployment/redis or /etc/ansible/roles/redis
```

However, it works when I rename the role to `DavidWittman.redis`
